spring:
  datasource:
    url: mydb.cw5kc6m6yvdi.us-east-1.rds.amazonaws.com:3306
    password: kt6aiNeQ026wf2zwEgcl
    username: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  web:
    resources:
      static-locations: classpath:/