server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://database-1.cw5kc6m6yvdi.us-east-1.rds.amazonaws.com:3306/apiPlay
    password: qwerty123
    username: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  web:
    resources:
      static-locations: classpath:/